---
- hosts: master
  vars:
    packages:
      - elasticsearch
      - kibana
      - logstash
  tasks:
    - name: remove ELK packages
      yum:
        name: "{{ packages }}"
        state: removed
    - name: remove ELK config dirs
      file:
        path: "/etc/{{ item }}"
        state: absent
      loop: "{{ packages }}"
    - name: remove ELK data dirs
      file:
        path: "/var/lib/{{ item }}"
        state: absent
      loop: "{{ packages }}"
      