---
- hosts: server
  become: true
  tasks:
  - name: Verifying Java dependencies
    yum: 
      name: java-1.8.0-openjdk
      state: present
  - name: Adding ELK repository
    rpm_key: 
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    copy:
      src: sources/yum.repos.d/elasticsearch.repo
      dest: /etc/yum.repos.d/elasticsearch.repo
  - 

