---
- import_playbook: playbooks/elk_server.yml

# Commented since clients are installed in the cluster's Ansible
# - import_playbook: playbooks/master.yml
# - import_playbook: playbooks/computes.yml
