---
- name: enable_restart_elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    enabled: yes

- name: enable_restart_kibana
  systemd:
    name: kibana
    state: restarted
    enabled: yes

- name: enable_restart_logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes 
