---
- name: Configuring elasticsearch and kibana
  template:
    src: "etc/{{ item }}/{{ item }}.yml.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
  notify: "Restarting {{ item }} service"
  loop:
    - elasticsearch
    - kibana
