---
- name: Configuring logstash filters
  copy:
    src: etc/logstash/conf.d/10-custom-filter.conf
    dest: /etc/logstash/conf.d/10-custom-filter.conf
  notify: 
  - Restarting logstash service
  - Enabling logstash service
- name: Configuring logstash input/output
  template:
    src: "{{ item.src }}"
    dest: "/etc/logstash/{{ item.path }} | regex_replace('\\.j2$', '') }}"
  with_filetree: "roles/rsyslog_server/templates/etc/logstash"
  notify: 
  - Restarting logstash service
  - Enabling logstash service
  when: item.state == 'file'
