---
- name: Configuring rsyslog core
  copy: 
    src: etc/rsyslog.conf
    dest: /etc/rsyslog.conf
  notify:  Restarting rsyslog service
- name: Configuring rsyslog forwarding
  copy:
    src: etc/rsyslog.d/01-json-template.conf
    dest: /etc/rsyslog.d/01-json-template.conf
  template:
    src: etc/rsyslog.d/10-output.conf.j2
    dest: /etc/rsyslog.d/10-output.conf
  notify:  Restarting rsyslog service
