---
- name: Restarting rsyslog service
  service:
      name: rsyslog
      state: restarted
      enabled: yes
  listen: Restart rsyslog service 
- name: Enabling rsyslog service
  command: systemctl enable rsyslog
  listen: Restart rsyslog service 
