---
- name: Restarting elasticsearch service
  service:
      name: elasticsearch
      state: restarted
      enabled: yes
  listen: Restart elasticsearch service
- name: Enabling elasticsearch service
  command: systemctl enable elasticsearch
  listen: Restart elasticsearch service
- name: Restarting kibana service
  service:
      name: kibana
      state: restarted
      enabled: yes
  listen: Restart kibana service 
- name: Enabling kibana service
  command: systemctl enable kibana
  listen: Restart kibana service 
- name: Restarting logstash service
  service:
      name: logstash
      state: restarted
      enabled: yes
  listen: Restart logstash service 
- name: Enabling logstash service
  command: systemctl enable logstash
  listen: Restart logstash service 
- name: Restarting rsyslog service
  service:
      name: rsyslog
      state: restarted
      enabled: yes
  listen: Restart rsyslog service 
- name: Enabling rsyslog service
  command: systemctl enable rsyslog
  listen: Restart rsyslog service 
