---
- name: Restarting rsyslog service
  service:
      name: rsyslog
      state: restarted
      enabled: yes
  command: systemctl enable rsyslog
- name: Restarting elasticsearch service
  service:
      name: elasticsearch
      state: restarted
      enabled: yes
  command: systemctl enable elasticsearch
- name: Restarted kibana service
  service:
      name: kibana
      state: restarted
      enabled: yes
  command: systemctl enable
- name: Restarted logstash service
  service:
      name: logstash
      state: restarted
      enabled: yes
  command: systemctl enable logstash
