---
- name: Restarting rsyslog service
  service:
      name: rsyslog
      state: restarted
      enabled: yes
- name: Starting elasticsearch service
  service:
      name: elasticsearch
      state: started
      enabled: yes
- name: Starting kibana service
  service:
      name: kibana
      state: started
      enabled: yes
- name: Starting logstash service
  service:
      name: logstash
      state: started
      enabled: yes
