---
- name: Configure elasticsearch
  template:
    src: "etc/elasticsearch/elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  notify: 
    - enable_restart_elasticsearch
    - create_indexes_mappings

- name: Create dead_letter_queue directory if it does not exist
  file:
    path: /var/log/logstash/dead_letter_queue
    state: directory
    mode: 0755

- name: Configure logstash
  copy:
    src: "etc/logstash/{{ item }}"
    dest: "/etc/logstash/{{ item }}"
    mode: 0644
  with_items:
    - pipelines.yml
    - logstash.yml
  notify: enable_restart_logstash

- name: Configure logstash input
  copy:
    src: etc/logstash/conf.d/01-input.conf
    dest: /etc/logstash/conf.d/01-input.conf
    mode: 0644
  notify: enable_restart_logstash

- name: Configure logstash filters
  copy:
    src: etc/logstash/conf.d/02-filter.conf
    dest: /etc/logstash/conf.d/02-filter.conf
    mode: 0644
  notify: enable_restart_logstash

- name: Configure logstash output
  template:
    src: etc/logstash/conf.d/03-output.conf.j2
    dest: /etc/logstash/conf.d/03-output.conf
    mode: 0644
  notify: enable_restart_logstash

- name: Configure kibana
  template:
    src: "etc/kibana/kibana.yml.j2"
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: 
    - enable_restart_kibana
    - import_dashboard
